#! /bin/sh

# AUTOSTART
sxhkd &
picom -b -d :0 &
feh --bg-scale /usr/share/backgrounds/ &
wal -R &
$HOME/.config/polybar/launch.sh &
# Rescuetime Start Script:
$HOME/scripts/launch.sh &
timekprd & 

bspc monitor eDP1 -d 
bspc monitor HDMI1 -d         

bspc config border_width         5
bspc config window_gap          30
bspc config top_padding 60
bspc config left_padding 30
bspc config right_padding 30
bspc config border_radius 15

highlight="#B93A5C"
background="#4561B1"
bspc config focused_border_color "$highlight"
bspc config normal_border_color "$background"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Spotify desktop='^0'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

